# Generated by Django 5.2.7 on 2025-10-25 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('non_fiction', 'Нехудожественная литература'), ('fantasy', 'Фэнтези'), ('sci_fi', 'Научная фантастика'), ('mystery', 'Детектив'), ('romance', 'Роман'), ('biography', 'Биография'), ('history', 'История'), ('science', 'Наука'), ('other', 'Другое')], max_length=50, verbose_name='Жанр')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'Хочу прочитать'), ('reading', 'Читаю'), ('finished', 'Прочитано')], default='want_to_read', max_length=20, verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оценка')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Дата начала чтения')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='Дата окончания чтения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, verbose_name='Год')),
                ('target_books', models.IntegerField(default=12, verbose_name='Цель по книгам')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
